CREATE TABLE products (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

    name VARCHAR(255) NOT NULL,

    category VARCHAR(100) NOT NULL,

    price DECIMAL(10, 2) NOT NULL DEFAULT 0.00,

    stock INT NOT NULL DEFAULT 0,

    status ENUM('Active', 'Inactive', 'Out of Stock')
        NOT NULL DEFAULT 'Active',

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP
);